const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.TextBox,
		C3.Plugins.sliderbar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Button.Exps.X,
		C3.Plugins.Button.Exps.Y,
		C3.Plugins.Button.Acts.MoveToTop,
		C3.Plugins.Button.Acts.MoveToBottom,
		C3.Plugins.TextBox.Cnds.OnClicked,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.sliderbar.Cnds.OnClicked,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Intro: 0},
	{SettleThis: 0},
	{Question: 0},
	{OptionOne: 0},
	{OptionTwo: 0},
	{InternetDecision: 0},
	{NextQuestion: 0},
	{MakeQuestion: 0},
	{MakeOptionOne: 0},
	{MakeOptionTwo: 0},
	{PlayerQuestionDecision: 0},
	{PreviewQuestion: 0},
	{MakeAQuestion: 0},
	{InternetPercentDecision: 0},
	{QuestionsAnsweredSoFar: 0},
	{OneBias: 0},
	{TwoBias: 0},
	{MakeQuestionHasBeenClicked: 0},
	{MakeOptionOneHasBeenClicked: 0},
	{MakeOptionTwoHasBeenClicked: 0},
	{MakePercentageDecided: 0},
	{FinishedQuestions: 0},
	{MadeAQuestion: 0}
];

self.InstanceType = {
	Intro: class extends self.ITextInstance {},
	SettleThis: class extends self.IButtonInstance {},
	Question: class extends self.ITextInstance {},
	OptionOne: class extends self.IButtonInstance {},
	OptionTwo: class extends self.IButtonInstance {},
	InternetDecision: class extends self.IProgressBarInstance {},
	NextQuestion: class extends self.IButtonInstance {},
	MakeQuestion: class extends self.ITextInputInstance {},
	MakeOptionOne: class extends self.ITextInputInstance {},
	MakeOptionTwo: class extends self.ITextInputInstance {},
	PlayerQuestionDecision: class extends self.ISliderBarInstance {},
	PreviewQuestion: class extends self.IButtonInstance {},
	MakeAQuestion: class extends self.IButtonInstance {}
}