const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Turret,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Path: 0},
	{Spawner: 0},
	{base: 0},
	{Zhealth: 0},
	{Pathfinding: 0},
	{Zombies: 0},
	{BZhealth: 0},
	{BossZombie: 0},
	{Turret: 0},
	{WatchTower: 0},
	{StarterUnit: 0},
	{Solid: 0},
	{Land: 0},
	{Menu: 0},
	{StartNewWave: 0},
	{Bullet: 0},
	{Touch: 0},
	{Logo: 0},
	{PlayRound: 0},
	{SBG: 0},
	{Help: 0},
	{Done: 0},
	{WaveTEXT: 0},
	{MoneyTEXT: 0},
	{HealthTEXT: 0},
	{ShopText1: 0},
	{DragDrop: 0},
	{StarterUnitIcon: 0},
	{WINTEXT: 0},
	{WINBG: 0},
	{LOSETEXT: 0},
	{LOSEBG: 0},
	{HELPBG: 0},
	{HELPT: 0},
	{InstructionTEXT: 0},
	{WatchTowericon: 0},
	{Turrettext: 0},
	{INFO: 0},
	{Wave: 0},
	{WaveBegun: 0},
	{AmountOfZombies: 0},
	{ZombiesNotSpawned: 0},
	{Health: 0},
	{Money: 0},
	{ZombiesKilled: 0},
	{clicks: 0}
];

self.InstanceType = {
	Path: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	Zombies: class extends self.ISpriteInstance {},
	BossZombie: class extends self.ISpriteInstance {},
	WatchTower: class extends self.ISpriteInstance {},
	StarterUnit: class extends self.ISpriteInstance {},
	Land: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	StartNewWave: class extends self.IButtonInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Logo: class extends self.ITextInstance {},
	PlayRound: class extends self.IButtonInstance {},
	SBG: class extends self.ITiledBackgroundInstance {},
	Help: class extends self.IButtonInstance {},
	Done: class extends self.IButtonInstance {},
	WaveTEXT: class extends self.ITextInstance {},
	MoneyTEXT: class extends self.ITextInstance {},
	HealthTEXT: class extends self.ITextInstance {},
	ShopText1: class extends self.ITextInstance {},
	StarterUnitIcon: class extends self.ISpriteInstance {},
	WINTEXT: class extends self.ITextInstance {},
	WINBG: class extends self.ITiledBackgroundInstance {},
	LOSETEXT: class extends self.ITextInstance {},
	LOSEBG: class extends self.ITiledBackgroundInstance {},
	HELPBG: class extends self.ITiledBackgroundInstance {},
	HELPT: class extends self.ITextInstance {},
	InstructionTEXT: class extends self.ITextInstance {},
	WatchTowericon: class extends self.ISpriteInstance {},
	Turrettext: class extends self.ITextInstance {},
	INFO: class extends self.ITextInstance {}
}