const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Tween: 0},
	{MoveTo: 0},
	{MoveTo2: 0},
	{player: 0},
	{Solid: 0},
	{platform: 0},
	{Anchor: 0},
	{lives: 0},
	{Sine: 0},
	{enemy: 0},
	{flyingEnemy: 0},
	{portalEntrance: 0},
	{teleporter: 0},
	{kilbrick: 0},
	{gameOverText: 0},
	{keyboard: 0},
	{restart: 0},
	{note: 0},
	{explanationnote: 0},
	{textForNote: 0},
	{leaveNoteOne: 0},
	{TiledBackground: 0},
	{Pin: 0},
	{darkness: 0},
	{lantern: 0},
	{portalLv2: 0},
	{noteTwo: 0},
	{noteText2: 0},
	{exitNote2: 0},
	{dynamite: 0},
	{flareGun: 0},
	{dynamiteHitbox: 0},
	{leaveFlareGun: 0},
	{FlareGunParticles: 0},
	{Bullet: 0},
	{flaregunpath: 0},
	{rope2: 0},
	{rope2End: 0},
	{rope2start: 0},
	{rope2b: 0},
	{rope2c: 0},
	{rope1: 0},
	{rope15: 0},
	{explosion: 0},
	{portal2: 0},
	{dynamiteexplotion: 0},
	{endingBg: 0},
	{dirt: 0},
	{cloud: 0},
	{cloud2: 0},
	{car: 0},
	{win: 0},
	{playerwin: 0},
	{playerPos: 0},
	{timer: 0},
	{finish: 0},
	{Darkness: 0},
	{playerflareGun: 0},
	{FlareGunactivate: 0},
	{PlayerTime: 0},
	{TimeTrue: 0},
	{flaregunskina: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	lives: class extends self.ITextInstance {},
	enemy: class extends self.ISpriteInstance {},
	flyingEnemy: class extends self.ISpriteInstance {},
	portalEntrance: class extends self.ISpriteInstance {},
	teleporter: class extends self.ISpriteInstance {},
	kilbrick: class extends self.ISpriteInstance {},
	gameOverText: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	restart: class extends self.IButtonInstance {},
	note: class extends self.ISpriteInstance {},
	explanationnote: class extends self.ISpriteInstance {},
	textForNote: class extends self.ITextInstance {},
	leaveNoteOne: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	darkness: class extends self.ITiledBackgroundInstance {},
	lantern: class extends self.ISpriteInstance {},
	portalLv2: class extends self.ISpriteInstance {},
	noteTwo: class extends self.ISpriteInstance {},
	noteText2: class extends self.ITextInstance {},
	exitNote2: class extends self.IButtonInstance {},
	dynamite: class extends self.ISpriteInstance {},
	flareGun: class extends self.ISpriteInstance {},
	dynamiteHitbox: class extends self.ISpriteInstance {},
	leaveFlareGun: class extends self.IButtonInstance {},
	FlareGunParticles: class extends self.IParticlesInstance {},
	flaregunpath: class extends self.IParticlesInstance {},
	rope2: class extends self.ISpriteInstance {},
	rope2End: class extends self.ISpriteInstance {},
	rope2start: class extends self.ISpriteInstance {},
	rope2b: class extends self.ISpriteInstance {},
	rope2c: class extends self.ISpriteInstance {},
	rope1: class extends self.ISpriteInstance {},
	rope15: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	dynamiteexplotion: class extends self.IParticlesInstance {},
	endingBg: class extends self.ITiledBackgroundInstance {},
	dirt: class extends self.ITiledBackgroundInstance {},
	cloud: class extends self.ISpriteInstance {},
	cloud2: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	win: class extends self.ITextInstance {},
	playerwin: class extends self.ISpriteInstance {},
	playerPos: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	finish: class extends self.IButtonInstance {}
}