const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Behaviors.Follow,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Anchor,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.shadowlight,
		C3.Plugins.Tilemap,
		C3.Behaviors.wrap,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{"3DShape": 0},
	{Solid: 0},
	{"3DShape2": 0},
	{yaLife: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Follow: 0},
	{Pathfinding: 0},
	{Sprite2: 0},
	{Particles: 0},
	{Pin: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{tutorialText: 0},
	{Sprite6: 0},
	{Sine: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{"3DShape3": 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{Sprite9: 0},
	{Rotate: 0},
	{TiledBackground9: 0},
	{Text: 0},
	{MoveTo: 0},
	{Sprite10: 0},
	{Anchor: 0},
	{Text2: 0},
	{Text3: 0},
	{"3DShape4": 0},
	{"3DShape5": 0},
	{TiledBackground10: 0},
	{Sine2: 0},
	{Sprite11: 0},
	{ShadowCaster: 0},
	{"3DShape6": 0},
	{TiledBackground11: 0},
	{Sprite12: 0},
	{Particles2: 0},
	{TiledBackground12: 0},
	{DragDrop: 0},
	{Sprite13: 0},
	{Audio: 0},
	{"3DShape7": 0},
	{TiledBackground13: 0},
	{"3DShape8": 0},
	{Sprite14: 0},
	{ShadowLight: 0},
	{"3DShape9": 0},
	{TiledBackground14: 0},
	{TiledBackground15: 0},
	{Particles3: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Tilemap: 0},
	{Wrap: 0},
	{TiledBackground16: 0},
	{Text4: 0},
	{Variable1: 0},
	{Variable2: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	tutorialText: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	_3DShape4: class extends self.I3DShapeInstance {},
	_3DShape5: class extends self.I3DShapeInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	_3DShape6: class extends self.I3DShapeInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	_3DShape7: class extends self.I3DShapeInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	_3DShape8: class extends self.I3DShapeInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	_3DShape9: class extends self.I3DShapeInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {}
}