const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.Car,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Behaviors.Car.Acts.SetDeceleration,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Player1: 0},
	{Player2: 0},
	{Keyboard: 0},
	{Solid: 0},
	{Ground: 0},
	{Wall: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{FallingObject: 0},
	{playerOneFoodCount: 0},
	{PlayerTwoScore: 0},
	{Space: 0},
	{Earth: 0},
	{Meteor: 0},
	{Car: 0},
	{ShipPlayerOne: 0},
	{ShipPlayerTwo: 0},
	{Sine: 0},
	{BlackHole: 0},
	{DeathWall: 0},
	{Rotate: 0},
	{BurgerFood: 0},
	{PlayerTwoPet: 0},
	{PlayerOnePet: 0},
	{PlayerOneFoodButton: 0},
	{PlayerTwoFoodButton: 0},
	{PlayerTwoHealth: 0},
	{PlayerOnePetHealth: 0},
	{FallingObjetMiniGame: 0},
	{ShipRacingMiniGame: 0},
	{PlayButton: 0},
	{YouWinPlayerOne: 0},
	{YouWinPlayerTwo: 0},
	{Backgroundhomescreen: 0},
	{fallingobjectbackground: 0},
	{YouWinBackground: 0},
	{otherbgfo: 0},
	{Text: 0},
	{instruction1: 0},
	{instruction2: 0},
	{instruction3: 0},
	{instruction4: 0},
	{instruction5: 0},
	{instruction6: 0},
	{instruction7: 0},
	{credits: 0},
	{bginstructions: 0},
	{ufoinstructions: 0},
	{Audio: 0},
	{EasterEgg: 0},
	{Mouse: 0},
	{instruction10: 0},
	{Text2: 0},
	{Fade: 0},
	{SpaceBeam: 0},
	{Score: 0},
	{Score2: 0},
	{HomeScreen: 0},
	{PlayerTwoPetHealth: 0}
];

self.InstanceType = {
	Player1: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ground: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	FallingObject: class extends self.ISpriteInstance {},
	playerOneFoodCount: class extends self.ITextInstance {},
	PlayerTwoScore: class extends self.ITextInstance {},
	Space: class extends self.ISpriteInstance {},
	Earth: class extends self.ISpriteInstance {},
	Meteor: class extends self.ISpriteInstance {},
	ShipPlayerOne: class extends self.ISpriteInstance {},
	ShipPlayerTwo: class extends self.ISpriteInstance {},
	BlackHole: class extends self.ISpriteInstance {},
	DeathWall: class extends self.ISpriteInstance {},
	BurgerFood: class extends self.ISpriteInstance {},
	PlayerTwoPet: class extends self.ISpriteInstance {},
	PlayerOnePet: class extends self.ISpriteInstance {},
	PlayerOneFoodButton: class extends self.IButtonInstance {},
	PlayerTwoFoodButton: class extends self.IButtonInstance {},
	PlayerTwoHealth: class extends self.ITextInstance {},
	PlayerOnePetHealth: class extends self.ITextInstance {},
	FallingObjetMiniGame: class extends self.IButtonInstance {},
	ShipRacingMiniGame: class extends self.IButtonInstance {},
	PlayButton: class extends self.IButtonInstance {},
	YouWinPlayerOne: class extends self.ITextInstance {},
	YouWinPlayerTwo: class extends self.ITextInstance {},
	Backgroundhomescreen: class extends self.ISpriteInstance {},
	fallingobjectbackground: class extends self.ISpriteInstance {},
	YouWinBackground: class extends self.ISpriteInstance {},
	otherbgfo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	instruction1: class extends self.ITextInstance {},
	instruction2: class extends self.ITextInstance {},
	instruction3: class extends self.ITextInstance {},
	instruction4: class extends self.ITextInstance {},
	instruction5: class extends self.ITextInstance {},
	instruction6: class extends self.ITextInstance {},
	instruction7: class extends self.ITextInstance {},
	credits: class extends self.ITextInstance {},
	bginstructions: class extends self.ISpriteInstance {},
	ufoinstructions: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	EasterEgg: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	instruction10: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	SpaceBeam: class extends self.ISpriteInstance {}
}