const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{title: 0},
	{Start: 0},
	{Tiemonblock: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{blue: 0},
	{Space: 0},
	{Yelloow: 0},
	{red: 0},
	{green: 0},
	{Orange: 0},
	{Black: 0},
	{sun: 0},
	{Pages: 0},
	{Frame1: 0},
	{HowToPlay: 0},
	{General: 0},
	{frame3: 0},
	{SpaceTravel: 0},
	{frame4: 0},
	{Bluedescription: 0},
	{yellowdescription: 0},
	{greendescription: 0},
	{reddescription: 0},
	{Orangedescription: 0},
	{Blackdescription: 0},
	{Sundescription: 0},
	{POWERS: 0},
	{Car: 0},
	{Solid: 0},
	{Ship: 0},
	{wall: 0},
	{download: 0},
	{NeptuneLand: 0},
	{Frame6: 0},
	{download2: 0},
	{signtomegamouse: 0},
	{Water: 0},
	{download3: 0},
	{Puddle: 0},
	{Keyboard: 0},
	{void: 0},
	{download4: 0},
	{lowgas: 0},
	{Uranus: 0},
	{download5: 0},
	{cie: 0},
	{gas: 0},
	{Switch: 0},
	{images: 0},
	{Text: 0},
	{Turret: 0},
	{Primal_Render_: 0},
	{Bullet: 0},
	{arrow: 0},
	{Sprite: 0},
	{download6: 0},
	{download7: 0},
	{download8: 0},
	{Redspotback: 0},
	{cobweb: 0},
	{grass: 0},
	{Tnt: 0},
	{Jackolantern: 0},
	{obsidian: 0},
	{jupiterland: 0},
	{yellowcage: 0},
	{chain: 0},
	{jupiterbos: 0},
	{sign2: 0},
	{youwinback: 0},
	{sign3: 0},
	{play: 0},
	{wall2: 0},
	{tnt2: 0},
	{reinforcfedcobweb: 0},
	{Audio: 0}
];

self.InstanceType = {
	title: class extends self.ITextInstance {},
	Start: class extends self.IButtonInstance {},
	blue: class extends self.ISpriteInstance {},
	Space: class extends self.ISpriteInstance {},
	Yelloow: class extends self.ISpriteInstance {},
	red: class extends self.ISpriteInstance {},
	green: class extends self.ISpriteInstance {},
	Orange: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	Pages: class extends self.ISpriteInstance {},
	Frame1: class extends self.ISpriteInstance {},
	HowToPlay: class extends self.ITextInstance {},
	General: class extends self.ITextInstance {},
	frame3: class extends self.ISpriteInstance {},
	SpaceTravel: class extends self.ITextInstance {},
	frame4: class extends self.ISpriteInstance {},
	Bluedescription: class extends self.ITextInstance {},
	yellowdescription: class extends self.ITextInstance {},
	greendescription: class extends self.ITextInstance {},
	reddescription: class extends self.ITextInstance {},
	Orangedescription: class extends self.ITextInstance {},
	Blackdescription: class extends self.ITextInstance {},
	Sundescription: class extends self.ITextInstance {},
	POWERS: class extends self.ITextInstance {},
	Ship: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	NeptuneLand: class extends self.ISpriteInstance {},
	Frame6: class extends self.ISpriteInstance {},
	download2: class extends self.ISpriteInstance {},
	signtomegamouse: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	download3: class extends self.ISpriteInstance {},
	Puddle: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	void: class extends self.ISpriteInstance {},
	download4: class extends self.ISpriteInstance {},
	lowgas: class extends self.ITextInstance {},
	Uranus: class extends self.ISpriteInstance {},
	download5: class extends self.ISpriteInstance {},
	cie: class extends self.ISpriteInstance {},
	gas: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Primal_Render_: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	download6: class extends self.ISpriteInstance {},
	download7: class extends self.ISpriteInstance {},
	download8: class extends self.ISpriteInstance {},
	Redspotback: class extends self.ISpriteInstance {},
	cobweb: class extends self.ISpriteInstance {},
	grass: class extends self.ISpriteInstance {},
	Tnt: class extends self.ISpriteInstance {},
	Jackolantern: class extends self.ISpriteInstance {},
	obsidian: class extends self.ISpriteInstance {},
	jupiterland: class extends self.ISpriteInstance {},
	yellowcage: class extends self.ISpriteInstance {},
	chain: class extends self.ISpriteInstance {},
	jupiterbos: class extends self.ISpriteInstance {},
	sign2: class extends self.ISpriteInstance {},
	youwinback: class extends self.ISpriteInstance {},
	sign3: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {},
	tnt2: class extends self.ISpriteInstance {},
	reinforcfedcobweb: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}