const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.progressbar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Bob: 0},
	{Solid: 0},
	{platform: 0},
	{door: 0},
	{Sine: 0},
	{Sprite3: 0},
	{Anchor: 0},
	{lives: 0},
	{SpriteFont: 0},
	{Gameovertext: 0},
	{MoveTo: 0},
	{Pie: 0},
	{gameOverButton: 0},
	{Text: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{instructionText: 0},
	{instructionButton: 0},
	{TiledBackground6: 0},
	{level2Text: 0},
	{Sprite2: 0},
	{winnerLev3button: 0},
	{goToWinScreen: 0},
	{TiledBackground7: 0},
	{Text2: 0},
	{playAgainWinButton: 0},
	{Audio: 0},
	{ProgressBar: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{bonusButton: 0},
	{Text3: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Bob: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	lives: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Gameovertext: class extends self.ITextInstance {},
	Pie: class extends self.ISpriteInstance {},
	gameOverButton: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	instructionText: class extends self.ITextInstance {},
	instructionButton: class extends self.IButtonInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	level2Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	winnerLev3button: class extends self.IButtonInstance {},
	goToWinScreen: class extends self.ITextInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	playAgainWinButton: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	bonusButton: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {}
}