const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Camera3D,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{bienKitty: 0},
	{Platform: 0},
	{goodkitty: 0},
	{"3DCamera": 0},
	{Solid: 0},
	{platform: 0},
	{Sine: 0},
	{Sine2: 0},
	{BADKITTY: 0},
	{"8Direction": 0},
	{"8Direction2": 0},
	{player: 0},
	{background: 0},
	{backgrpund: 0},
	{Text: 0},
	{Lives: 0},
	{idk: 0},
	{BADKITT: 0},
	{Button: 0},
	{Button2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{btn_play: 0},
	{Touch: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{spr_control: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{spr_player: 0},
	{spr_player2: 0},
	{spr_enemy: 0},
	{Sprite6: 0},
	{btn_paused: 0},
	{par_enemy: 0},
	{par_player2: 0},
	{spr_player3: 0},
	{par_enemy2: 0},
	{txt_score: 0},
	{txt_highscoreScore2: 0},
	{gamePaused: 0},
	{score: 0},
	{isAlive: 0},
	{highscore: 0},
	{catsspeed: 0}
];

self.InstanceType = {
	bienKitty: class extends self.ISpriteInstance {},
	goodkitty: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	platform: class extends self.ISpriteInstance {},
	BADKITTY: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	background: class extends self.ITiledBackgroundInstance {},
	backgrpund: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Lives: class extends self.ITextInstance {},
	idk: class extends self.ISpriteInstance {},
	BADKITT: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	spr_control: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	spr_player2: class extends self.ISpriteInstance {},
	spr_enemy: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	btn_paused: class extends self.ISpriteInstance {},
	par_enemy: class extends self.IParticlesInstance {},
	par_player2: class extends self.IParticlesInstance {},
	spr_player3: class extends self.ISpriteInstance {},
	par_enemy2: class extends self.IParticlesInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_highscoreScore2: class extends self.ITextInstance {}
}