const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Acts.SetTooltip,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{FlipMe: 0},
	{HeadsHasFlipped: 0},
	{Coin: 0},
	{HeadsChance: 0},
	{MoneyAmount: 0},
	{HeadsChanceCounter: 0},
	{FlipSpeed: 0},
	{UpgradeBaseWorth: 0},
	{CombosUpgrade: 0},
	{HeadsCounter: 0},
	{YouWon: 0},
	{HeadsTailsList: 0},
	{Money: 0},
	{BaseWorth: 0},
	{HeadsChanceBase: 0},
	{HeadsChance30: 0},
	{HeadsChance40: 0},
	{HeadsChance50: 0},
	{HeadsChance60: 0},
	{CoinType: 0},
	{HeadsCounting: 0},
	{HeadsFlippingChance: 0},
	{HeadsInRow: 0},
	{FlipSpeed025: 0},
	{FlipSpeed020: 0},
	{FlipSpeed015: 0},
	{FlipSpeed010: 0},
	{CoinFace: 0},
	{Combos1point5: 0},
	{Combos2point0: 0},
	{Combos1point0: 0},
	{ComboMoney: 0},
	{NotFlippedYet: 0},
	{FinalFlipOutcome: 0},
	{NotFinalFlipYet: 0},
	{FlipHistory: 0}
];

self.InstanceType = {
	FlipMe: class extends self.IButtonInstance {},
	Coin: class extends self.ISpriteInstance {},
	HeadsChance: class extends self.IButtonInstance {},
	MoneyAmount: class extends self.ITextInstance {},
	HeadsChanceCounter: class extends self.ITextInstance {},
	FlipSpeed: class extends self.IButtonInstance {},
	UpgradeBaseWorth: class extends self.IButtonInstance {},
	CombosUpgrade: class extends self.IButtonInstance {},
	HeadsCounter: class extends self.ITextInstance {},
	YouWon: class extends self.ITextInstance {},
	HeadsTailsList: class extends self.ITextInstance {}
}