const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{gameoverbackground: 0},
	{youwinbackground: 0},
	{GameOverText: 0},
	{PlayAgain: 0},
	{Solid: 0},
	{wall: 0},
	{BoundToLayout: 0},
	{frog: 0},
	{fly: 0},
	{goldenfly: 0},
	{level1Snake: 0},
	{level2Snake: 0},
	{level3snake: 0},
	{youWinText: 0},
	{Keyboard: 0},
	{lives: 0},
	{score: 0},
	{Background: 0},
	{Play: 0},
	{InstructionsText: 0},
	{instructions: 0},
	{Audio: 0},
	{Score: 0},
	{Lives: 0},
	{lvl2snakesfalling: 0},
	{lvl3snakesfalling: 0}
];

self.InstanceType = {
	gameoverbackground: class extends self.ISpriteInstance {},
	youwinbackground: class extends self.ISpriteInstance {},
	GameOverText: class extends self.ITextInstance {},
	PlayAgain: class extends self.IButtonInstance {},
	wall: class extends self.ISpriteInstance {},
	frog: class extends self.ISpriteInstance {},
	fly: class extends self.ISpriteInstance {},
	goldenfly: class extends self.ISpriteInstance {},
	level1Snake: class extends self.ISpriteInstance {},
	level2Snake: class extends self.ISpriteInstance {},
	level3snake: class extends self.ISpriteInstance {},
	youWinText: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	lives: class extends self.ITextInstance {},
	score: class extends self.ITextInstance {},
	Background: class extends self.ISpriteInstance {},
	Play: class extends self.IButtonInstance {},
	InstructionsText: class extends self.ITextInstance {},
	instructions: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}