const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Physics,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Anchor: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{ScrollTo2: 0},
	{"8Direction": 0},
	{Physics: 0},
	{minion: 0},
	{ring: 0},
	{Pin: 0},
	{ringg: 0},
	{back_ring: 0},
	{keyboard: 0},
	{Solid: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{banana: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{instructions: 0},
	{Text2: 0},
	{Button: 0},
	{TiledBackground: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{cloud: 0},
	{Sprite17: 0},
	{Text: 0},
	{Button2: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{TiledBackground2: 0},
	{Sprite21: 0},
	{gameover: 0},
	{Sprite22: 0},
	{FLOOR123: 0},
	{lvl1music: 0},
	{timer: 0},
	{lives: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	minion: class extends self.ISpriteInstance {},
	ring: class extends self.ISpriteInstance {},
	ringg: class extends self.ISpriteInstance {},
	back_ring: class extends self.ISpriteInstance {},
	keyboard: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	banana: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	instructions: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	gameover: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	FLOOR123: class extends self.ISpriteInstance {},
	lvl1music: class extends self.IInstance {},
	timer: class extends self.ITextInstance {}
}