const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.jumpthru,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.MoveTo.Acts.MoveToObject
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Button: 0},
	{Text: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Video: 0},
	{yes: 0},
	{Sprite4: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite5: 0},
	{Solid: 0},
	{Sprite6: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite7: 0},
	{No: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Text4: 0},
	{Sprite11: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{ground: 0},
	{Sine: 0},
	{Sprite16: 0},
	{Text5: 0},
	{Text6: 0},
	{Sprite15: 0},
	{filler: 0},
	{Sprite17: 0},
	{Fish: 0},
	{Sprite18: 0},
	{Text7: 0},
	{Sprite19: 0},
	{easterEggs: 0},
	{Text8: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{bloodThingy: 0},
	{Sprite24: 0},
	{playAgain: 0},
	{Sprite25: 0},
	{restart: 0},
	{newGame: 0},
	{Sprite26: 0},
	{MoveTo: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sine2: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Jumpthru: 0},
	{jumpThrough: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Text9: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{wall1: 0},
	{wall2: 0},
	{Video2: 0},
	{invisibleButton: 0},
	{Sprite41: 0},
	{Mouse: 0},
	{wallThingy: 0},
	{Lives: 0},
	{lives1: 0},
	{lives2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	yes: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	No: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	filler: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	easterEggs: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	bloodThingy: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	playAgain: class extends self.IButtonInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	restart: class extends self.ITextInstance {},
	newGame: class extends self.IButtonInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	jumpThrough: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	wall1: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	invisibleButton: class extends self.IButtonInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	wallThingy: class extends self.ISpriteInstance {}
}